
platform :ios, '8.0'

use_frameworks!

target 'Segment-CleverTap_Example' do
  pod "Segment-CleverTap", :path => '../'
end

target 'Segment-CleverTap_Tests' do
  pod "Segment-CleverTap", :path => '../'

  pod 'Quick'
  pod 'Nimble'
  pod 'OCMock'
end
