source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

target 'Segment-CleverTap_Example' do
  pod "Segment-CleverTap", :path => '../'
end

target 'Segment-CleverTap_Tests' do
  pod "Segment-CleverTap", :path => '../'

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'
end
